services:
  - type: web
    name: kite-data-fetcher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CLOUD_DATABASE_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: KITE_API_KEY
        sync: false
      - key: KITE_API_SECRET
        sync: false
      - key: KITE_ACCESS_TOKEN
        sync: false
      - key: KITE_REDIRECT_URL
        sync: false
